"""Phase 2a: the crop catalog, farms, and plantings.

The first migration. Creates only the three tables Phase 2a's deliverable names, so
nothing here is schema written ahead of a feature that would write it.

Deliberately absent:

* `users` and `farms.user_id` — they arrive with authentication in Phase 2b. A
  nullable column added later is a cheap migration; a table nothing writes is not.
* `soil_profiles`, `weather_snapshots`, `advisories` — the architecture plan describes
  them, but soil and weather are computed per request and advisories are embedded in an
  analysis run. No code path writes any of the three today.
* `analysis_runs`, `crop_images` — still served from the in-memory store while the
  migration proceeds one service at a time.

Enum-valued columns are `String` with a `CHECK` rather than a native Postgres `ENUM`,
so the same migration runs on SQLite for the fast test tier.

`crops.sort_order` preserves the curated fixture order that the in-memory store got
free from dict insertion order. The frontend renders that list into a dropdown, so
falling back to alphabetical would be a visible change.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9d8c36ee73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scientific_name', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('season', sa.String(length=30), nullable=False),
    sa.Column('base_temp_c', sa.Float(), nullable=True),
    sa.Column('optimal_temp_min_c', sa.Float(), nullable=True),
    sa.Column('optimal_temp_max_c', sa.Float(), nullable=True),
    sa.Column('gdd_to_maturity', sa.Float(), nullable=True),
    sa.Column('water_need_mm_season', sa.Float(), nullable=True),
    sa.Column('ph_min', sa.Float(), nullable=True),
    sa.Column('ph_max', sa.Float(), nullable=True),
    sa.Column('drought_tolerance', sa.String(length=20), nullable=True),
    sa.Column('preferred_textures', sa.JSON(), nullable=False),
    sa.Column('common_diseases', sa.JSON(), nullable=False),
    sa.CheckConstraint("category IN ('cereal', 'legume', 'oilseed', 'vegetable', 'fruit', 'tuber', 'fibre', 'forage', 'other')", name=op.f('ck_crops_category_valid')),
    sa.CheckConstraint("drought_tolerance IS NULL OR drought_tolerance IN ('low', 'moderate', 'high')", name=op.f('ck_crops_drought_tolerance_valid')),
    sa.CheckConstraint("season IN ('spring', 'summer', 'autumn', 'winter', 'year_round')", name=op.f('ck_crops_season_valid')),
    sa.CheckConstraint('ph_max IS NULL OR (ph_max >= 0 AND ph_max <= 14)', name=op.f('ck_crops_ph_max_range')),
    sa.CheckConstraint('ph_min IS NULL OR (ph_min >= 0 AND ph_min <= 14)', name=op.f('ck_crops_ph_min_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crops'))
    )
    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crops_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_crops_sort_order'), ['sort_order'], unique=False)

    op.create_table('farms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('area_hectares', sa.Float(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('irrigation_type', sa.String(length=20), nullable=False),
    sa.Column('farming_practice', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("farming_practice IN ('conventional', 'organic', 'regenerative', 'mixed')", name=op.f('ck_farms_farming_practice_valid')),
    sa.CheckConstraint("irrigation_type IN ('rainfed', 'drip', 'sprinkler', 'flood', 'furrow', 'none')", name=op.f('ck_farms_irrigation_type_valid')),
    sa.CheckConstraint('area_hectares IS NULL OR area_hectares > 0', name=op.f('ck_farms_area_hectares_positive')),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name=op.f('ck_farms_latitude_range')),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name=op.f('ck_farms_longitude_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farms'))
    )
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.create_index('ix_farms_deleted_at', ['deleted_at'], unique=False)

    op.create_table('farm_crops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('crop_id', sa.Uuid(), nullable=False),
    sa.Column('planting_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('growth_stage', sa.String(length=20), nullable=False),
    sa.Column('area_hectares', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("growth_stage IN ('not_planted', 'germination', 'seedling', 'vegetative', 'flowering', 'fruiting', 'maturity', 'harvested')", name=op.f('ck_farm_crops_growth_stage_valid')),
    sa.CheckConstraint("status IN ('planned', 'growing', 'harvested', 'failed')", name=op.f('ck_farm_crops_status_valid')),
    sa.CheckConstraint('area_hectares IS NULL OR area_hectares > 0', name=op.f('ck_farm_crops_area_hectares_positive')),
    sa.CheckConstraint('planting_date IS NULL OR expected_harvest_date IS NULL OR expected_harvest_date >= planting_date', name=op.f('ck_farm_crops_harvest_after_planting')),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], name=op.f('fk_farm_crops_crop_id_crops')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_farm_crops_farm_id_farms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm_crops'))
    )
    with op.batch_alter_table('farm_crops', schema=None) as batch_op:
        batch_op.create_index('ix_farm_crops_farm_id', ['farm_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_crops', schema=None) as batch_op:
        batch_op.drop_index('ix_farm_crops_farm_id')

    op.drop_table('farm_crops')
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_index('ix_farms_deleted_at')

    op.drop_table('farms')
    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crops_sort_order'))
        batch_op.drop_index(batch_op.f('ix_crops_code'))

    op.drop_table('crops')
    # ### end Alembic commands ###
