"""Phase 2b: local users and farm ownership.

Extends the Phase 2a chain — it does not replace it.

`users` maps a Supabase account to a local identity by its `sub` claim. No password,
token, or secret is stored; `auth_id` is a public subject identifier.

`farms.user_id` is **nullable on purpose**. Farms created before authentication existed
have no owner, and making the column NOT NULL would either fail on a populated database
or require inventing an owner for rows that never had one. An unowned farm is readable
only by the demo user, so nothing leaks into an authenticated account. Ownership is
always assigned server-side from a verified token; no request body can set it.

`ON DELETE CASCADE` means removing a user removes their farms, which is the behaviour a
deletion request implies.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539ec596be65'
down_revision: Union[str, Sequence[str], None] = '8f9d8c36ee73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auth_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_auth_id'), ['auth_id'], unique=True)

    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_farms_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_farms_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_farms_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_farms_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_auth_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
